import { Button, VerticalBox, TextEdit , LineEdit, StandardButton, ComboBox, GroupBox, GridBox, TabWidget} from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> editor-text-tab1: "";
    in-out property<string> editor-text-tab2: "";
    in-out property<string> editor-text-tab3: "";
    in-out property<string> file-name: "";
    in-out property<string> tab1-name: "Tab 1";
    in-out property<string> tab2-name: "Tab 2";
    in-out property<string> tab3-name: "Tab 3";
    height: 300px;
    width: 500px;
    title: "Python Editor!";
    callback request-execute();
    callback request-save();
    callback show-popup();
    callback request-open();
    popup := PopupWindow {
        Rectangle {
            width: 200px;
            height: 100px;
            x: root.width/2 - self.width/2;
            y: root.height/2 - self.height/2;
            background: #434343;
            border-radius: 5px;
            VerticalBox {
                alignment: center;
                HorizontalLayout {
                    alignment: center;
                    Text {
                        font-size: 14px;
                        text: "File Name cannot be empty!";
                    }
                }
            }
        }
    }
    show-popup => {
        popup.show();
    }
    VerticalBox {
        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "Open";
                clicked => {
                    root.request-open();
                }
            }
            Button {
                text: "Save!";
                clicked => {
                    root.request-save();
                }
            }
            LineEdit {
                max-width: 0px;
                placeholder-text: "file name!";
                text: root.file-name;
                edited => {
                    root.file-name = self.text;
                }
            }
            Button {
                text: "Execute!";
                clicked => {
                    root.request-execute();
                }
            }
        }
        TabWidget {
            Tab {
                title: root.tab1-name;
                GridBox {
                    width: root.width;
                    TextEdit {
                        text: root.editor-text-tab1;
                        font-size: 16px;
                        height: root.height - 95px;
                        edited => {
                            root.editor-text-tab1 = self.text
                        }
                    }
                }
            }
            Tab {
                title: root.tab2-name;
                GridBox {
                    width: root.width;
                    TextEdit {
                        text: root.editor-text-tab2;
                        font-size: 16px;
                        height: root.height - 95px;
                        edited => {
                            root.editor-text-tab2 = self.text
                        }
                    }
                }
            }
            Tab {
                title: root.tab3-name;
                GridBox {
                    width: root.width;
                    TextEdit {
                        text: root.editor-text-tab3;
                        font-size: 16px;
                        height: root.height - 95px;
                        edited => {
                            root.editor-text-tab3 = self.text
                        }
                    }
                }
            }
        }
    }
}